### ISSUE TITLE
Extend email configuration

### ISSUE THREAD

**Issue by tobihans** [Ola-jed/Vue.Splash-API#6]
Setting up requires a Gmail account as it's hard coded as email host. Thus, the only requirements for the mail config to work
are the MailUser and MailPassword environment variables. I suggest to offer more flexibility by offering option to set mail host and other options like port number and TLS/SSL. So, we can use mock servers setup locally or services like Mailtrap to keep things cleaner.

**Comment by Ola-jed** [comment]
Updated but gmail is the default mail host.
